apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ss-notifier-api.name" . }}-nginx
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "ss-notifier-api.labels" . | nindent 4 }}
    component: nginx
spec:
  replicas: {{ .Values.nginx.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: {{ .Values.nginx.strategy.maxSurge | default 1 }}
      maxUnavailable: {{ .Values.nginx.strategy.maxUnavailable | default 0 }}
  selector:
    matchLabels:
      {{- include "ss-notifier-api.selectorLabels" . | nindent 6 }}
      component: nginx
  template:
    metadata:
      labels:
        {{- include "ss-notifier-api.selectorLabels" . | nindent 8 }}
        component: nginx
    spec:
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- range .Values.imagePullSecrets }}
        - name: {{ . }}
        {{- end }}
      {{- end }}
      {{- if .Values.nodeAffinity.enabled }}
      affinity:
        nodeAffinity:
          {{- if .Values.nodeAffinity.preferredNodes }}
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: {{ .Values.nodeAffinity.weight | default 30 }}
              preference:
                matchExpressions:
                  {{- range .Values.nodeAffinity.preferredNodes }}
                  - key: {{ .key }}
                    operator: {{ .operator }}
                    values:
                      {{- range .values }}
                      - {{ . | quote }}
                      {{- end }}
                  {{- end }}
          {{- end }}
          {{- if .Values.nodeAffinity.requiredNodes }}
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  {{- range .Values.nodeAffinity.requiredNodes }}
                  - key: {{ .key }}
                    operator: {{ .operator }}
                    values:
                      {{- range .values }}
                      - {{ . | quote }}
                      {{- end }}
                  {{- end }}
          {{- end }}
      {{- end }}
      containers:
      - name: nginx
        image: {{ include "ss-notifier-api.nginxImage" . }}
        imagePullPolicy: {{ .Values.nginx.image.pullPolicy }}
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
        resources:
          requests:
            cpu: 50m  
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi

