{{- if .Values.worker.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ss-notifier-api.name" . }}-worker
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "ss-notifier-api.labels" . | nindent 4 }}
    component: worker
spec:
  replicas: {{ .Values.worker.replicaCount }}
  selector:
    matchLabels:
      {{- include "ss-notifier-api.selectorLabels" . | nindent 6 }}
      component: worker
  template:
    metadata:
      labels:
        {{- include "ss-notifier-api.selectorLabels" . | nindent 8 }}
        component: worker
    spec:
      containers:
      - name: worker
        image: {{ include "ss-notifier-api.workerImage" . }}
        imagePullPolicy: {{ .Values.worker.image.pullPolicy }}
        envFrom:
        - configMapRef:
            name: {{ include "ss-notifier-api.name" . }}-config
        - secretRef:
            name: {{ include "ss-notifier-api.name" . }}-env
        resources:
          requests:
            cpu: 500m
            memory: 512Mi
          limits:
            cpu: 1000m
            memory: 1Gi
{{- end }}

