apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "ss-notifier-api.name" . }}-php-logs
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "ss-notifier-api.labels" . | nindent 4 }}
    component: php-logs
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: {{ .Values.phpLogs.storageSize | default "10Gi" }}

