apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ss-notifier-api.name" . }}-env
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  APP_KEY: "" 
  
  DB_PASSWORD: "" 
  
  REDIS_PASSWORD: "null"
  
  MAILGUN_SECRET: "" 
  MAIL_PASSWORD: "" 
  


