apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ss-notifier-api.name" . }}-postgresql
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  password: ""  # Set this via kubectl or Rancher

