apiVersion: v2
name: ss-notifier-api
description: A Helm chart for ss-notifier-api
type: application
version: 0.1.0
appVersion: "1.0"

dependencies:
  - name: elasticsearch
    version: 8.5.1
    repository: https://helm.elastic.co
    condition: elasticsearch.enabled
  - name: kibana
    version: 8.5.1
    repository: https://helm.elastic.co
    condition: kibana.enabled
